language: node_js
node_js:
  - "stable"
git:
  depth: 30
sudo:
  false
env:
  global: 
    - secure: "aPc53YSFV49t5axCq9cB7tOrCWREhtcWYOe+Mnfif+BZOR92xsSRjaISr/lCrHIpPtUYaBRJ9YELPamiC2eF1loXOWui+Id+GVqqLJA+DvrUYCyTInydTrQEH/d8TcpraJ8s2pT1jhxcwSXl97ScT/kVd4qWcHHC8Ngzp/i9TuY="
    - secure: "nn68j3NWmqH9wuBj686TXDX4cxoJbuU+15fMcAlEVKvgJFBv6G40KII/nqhy1D2Ht3PHIpIA5s5MJUxNMdzCeVir9Gn7XUHE6VtgKNOAPkcICpZiKla8e8XXg+o88Yyd0LEGQV/oxkTAKi4RNy/bKXhZZugV3jU/lXDvYmv9JKY="
    - secure: "H9X0IBiHZOE319yGfFlojN33VW6iRrZbGFNyxvu2KahOO615XMGdysknu1eagBO3HSADlhUhNiVTLt+VTcTe1uE8RfQMG3mPgNvI2t2EO7+6oP8mNBJAFVQi9vcc9YJBRBAfgrYrHDgZoUW9Sov5aMTHOTRB9NlQs4BlvypHLK0="
    - PORT=8080
    - MBAAS_DATABASE_NAME='mbaas'
script:
  npm run test && mocha -t 5000
